# Generated by Django 4.2.20 on 2025-03-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
