# Generated by Django 4.2.20 on 2025-03-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_team_draw_team_lose_team_win_alter_team_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
    ]
