# Generated by Django 4.2.20 on 2025-03-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_match_team2_alter_match_team1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='myapp.team'),
        ),
    ]
