# Generated by Django 4.2.20 on 2025-03-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_match_team1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='draw',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='lose',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
