# Generated by Django 4.2.20 on 2025-03-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='myapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='myapp.team'),
        ),
    ]
