# Generated by Django 4.2.20 on 2025-03-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
